### PR TITLE
Support Named types in pflags

### PR DESCRIPTION
**Pull request by EngHabu**
# TL;DR
Adding support for NamedTypes in pflags

## Type
 - [ ] Bug Fix
 - [X] Feature
 - [ ] Plugin

## Are all requirements met?

 - [X] Code completed
 - [X] Smoke tested
 - [X] Unit tests added
 - [X] Code documentation added
 - [X] Any pending items have an associated Issue

## Tracking Issue

fixes https://github.com/flyteorg/flyte/issues/1839

### CODE REVIEW

**Comment by evalsocket** [comment]
@EngHabu successfully generated the flags but getting error in compile time 
```
# github.com/flyteorg/flytectl/cmd/config/subcommand/sandbox
cmd/config/subcommand/sandbox/config_flags.go:56:18: cannot use &DefaultConfig.ImagePullPolicy (type *ImagePullPolicy) as type *int in argument to cmdFlags.IntVar
cmd/config/subcommand/sandbox/config_flags.go:56:111: cannot use DefaultConfig.ImagePullPolicy (type ImagePullPolicy) as type int in argument to cmdFlags.IntVar

```

**Comment by EngHabu** [comment]
@evalsocket mind trying the updated PR?

**Comment by evalsocket** [comment]
@EngHabu one more 
```
go build -o bin/flytectl -ldflags="-s -w -X github.com/flyteorg/flytestdlib/version.Version=v0.3.20-2-gae1eb07 -X github.com/flyteorg/flytestdlib/version.Build=ae1eb07 -X github.com/flyteorg/flytestdlib/version.BuildTime=2021-11-19" main.go
# github.com/flyteorg/flytectl/cmd/config/subcommand/sandbox
cmd/config/subcommand/sandbox/config_flags.go:56:18: cannot take the address of int(DefaultConfig.ImagePullPolicy)
```

Currently it is generating this 
```
cmdFlags.IntVar(&int(DefaultConfig.ImagePullPolicy), fmt.Sprintf("%v%v", prefix, "imagePullPolicy"), int(DefaultConfig.ImagePullPolicy), "Optional. Defines the image pull behavior.")
	
```
but it should be this 
```
cmdFlags.IntVar((*int)(&DefaultConfig.ImagePullPolicy), fmt.Sprintf("%v%v", prefix, "imagePullPolicy"), int(DefaultConfig.ImagePullPolicy), "Optional. Defines the image pull behavior.")
	
```

**Review by evalsocket — APPROVED** [review]
Fix lint and then we can  merge

**Review by evalsocket — APPROVED** [review]

**Pull request merged**
