### PR TITLE
Support binding pflags to default variable fields

### PR DESCRIPTION
**Pull request by EngHabu**
# TL;DR
- Update pflags cli tool to bind to the default var, this enables scenarios where pflags is used outside of config to just support strongly typed command line arguments.
- Add support for `maps` as a type for pflags

## Type
 - [ ] Bug Fix
 - [X] Feature
 - [ ] Plugin

### CODE REVIEW

**Comment by brucearctor** [comment]
Cool -- let me dig in more deeply (and actually pull code/test locally).

What's the general testing strategy/commitment?  

There are some new things that then aren't covered by tests.  At least superficially any of the specific things didn't seem problematic.

**Comment by brucearctor** [comment]
@EngHabu  -- was looking to use this review/PR as a chance to interact to learn more about perceived policies/culture/how-we-want-to-handle-stuff, in this project more generally.

**Comment by pmahindrakar-oss** [comment]
@EngHabu Please review when you get a chance.
I am consuming this in flytectl here https://github.com/flyteorg/flytectl/pull/70 and its working well

**Comment by EngHabu** [comment]
LGTM.. can somebody take one more look and approve?

**Review by pmahindrakar-oss — APPROVED** [review]

**Pull request merged**
